### ISSUE TITLE
reportOnly is removed from csp_policy which leads to unwanted behaviour

### ISSUE THREAD

**Issue by svleeuwen** [google/gae-secure-scaffold-python#14]
self.app.config is sometimes reused between requests.

When reportOnly is removed from the csp_policy [here](https://github.com/google/gae-secure-scaffold-python/blob/master/src/base/handlers.py#L205) the csp will behave as non-readonly on some consecutive requests. 

The reportOnly item should be removed because it's not a valid csp entity. But it should only be removed for the current request. A solution would be to take a copy of the csp_policy.

Only tested locally using `dev_appserver`

**Comment by pames** [comment]
Thanks for the report!  Will put together a fix soon.
