### ISSUE TITLE
Documentation doesn't match links and SDK installation paths

### ISSUE THREAD

**Issue by jeremenichelli** [google/gae-secure-scaffold-python#28]
On the fifth step it can be read:

> Visit https://developers.google.com/appengine/downloads, copy URL of "Linux/Other Platforms" zip file for current AppEngine SDK. Do this regardless of whether you are on Linux or OS X.

The link captioned as **"Linux/Other Platforms"** is not there anymore the main CTA inside that page actually points to the Google Cloud SDK which can be confusing.

In addition, installing the Google App Engine SDK from the old **.dmg** places its main folder in `/usr/local` and running

```sh
bash util.sh -d
```

fails since the script is looking for the development server in `/Users/<USER_NAME>/bin/google_appengine/dev_appserver.py`.

**Comment by pames** [comment]
Thanks for the report - I was just in the middle of revamping some of the documentation because we recently added Soy support for Python, so I'll be sure to test all the workflows and make sure we are up-to-date.

**Comment by jeremenichelli** [comment]
Thanks a lot for the quick response @pames, looking forward to hearing about this soon. Let me know if you need help testing the docs changing.

**Comment by pames** [comment]
FYI : You may want to take a look at https://github.com/google/gae-secure-scaffold-python/pull/29, as that contains refreshed documentation.  Feel free to comment if anything is unclear or doesn't work on your system.  As a side effect, I removed util.sh to simplify the number of toolchains we need to keep in sync - are you able to make do w/the Gruntfile?

**Comment by pames** [comment]
Hopefully addressed with #29

**Comment by jeremenichelli** [comment]
Hi @pames, thanks a lot for following this. I'm not assigned to the project anymore, if I have time I will take a look and come back with feedback or try to get one of my coworkers to take a look at the new documentation.

Cheers!
