### ISSUE TITLE
pip requirements.txt for all dependencies

### ISSUE THREAD

**Issue by kmturley** [google/gae-secure-scaffold-python#37]
Are you able to include a list of all the pip dependencies in one requirements.txt file? For example:

```
Django==1.11.25
gcloud==0.18.3
google-api-python-client==1.7.11
pylint==1.9.5
unittest2==1.1.0
webapp2==2.5.2
WebOb==1.8.5
```

These can then all be installed easily in one go using virtualenv and the command:

```
pip install virtualenv
virtualenv env && source env/bin/activate
pip install -r requirements.txt
```

**Comment by pames** [comment]
Hi, I'd be happy to review any such pull request, but one thing worth flagging is that webapp2 is python2 only and python2 is EOL in 2020: https://www.python.org/doc/sunset-python-2/

so this project should probably not be used in favor of another framework that will have better language/ecosystem support (unfortunately I don't have any recommendations for one with similar feature as this, my knowledge of this space is a bit dated at this point)

**Comment by kmturley** [comment]
Yeah makes sense, i'm guessing most will be moving to Python 3 before Jan 1st 2020.

We have some legacy Marketing projects which use this, which we are still supporting... but also wondering what the Brand Studio recommendation for Python 3 will be!

Thanks Phil
