### ISSUE TITLE
Not able to run closurebuilder.py in same directory

### ISSUE THREAD

**Issue by adaro** [google/gae-secure-scaffold-python#8]
Hi there and thanks for the awesome scaffolding. Any idea how to get around this issue? I followed the README but when I run grunt I get this error. I read a bit online [here](https://groups.google.com/forum/#!topic/closure-library-discuss/HgFwrhehHCk) and it seems like you can't have closurebuilder in the same directory as your app. Has anyone ran into this problem and have a straightforward solution? Thank you.

Grunt error below: 

> > Traceback (most recent call last):
> >   File "closure-library/closure/bin/build/closurebuilder.py", line 274, in <module>
> >     main()
> >   File "closure-library/closure/bin/build/closurebuilder.py", line 214, in main
> >     tree = depstree.DepsTree(sources)
> >   File "/Users/adaro/LFL/cbc-frontend/cbc-pledge-frontend/closure-library/closure/bin/build/depstree.py", line 48, in **init**
> >     provide, [self._provides_map[provide], source])
> > depstree.MultipleProvideError: Namespace "goog.events.BrowserFeature" provided more than once in sources:
> > PathSource closure-library/closure/goog/events/browserfeature.js
> > PathSource js/app.js
> > FAILED to run command for target: js

**Comment by adaro** [comment]
fixed this somehow

**Comment by jstone1984** [comment]
How did you solve it? Looking forward to your reply。my email:xialong1984@gmail.com
